//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public int AssocID { get; set; }
        public string AssocName { get; set; }
        public string addresse { get; set; }
        public int Nbrs_de_Membres { get; set; }
        public decimal budget_total { get; set; }
        public string code_postal { get; set; }
        public string description { get; set; }
        public string num_tele { get; set; }
    }
}
