//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membre()
        {
            this.Donation = new HashSet<Donation>();
            this.Payement = new HashSet<Payement>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string cin { get; set; }
        public string ville { get; set; }
        public string Code_Postal { get; set; }
        public string sexe { get; set; }
        public string email { get; set; }
        public string num_tele { get; set; }
        public System.DateTime date_naissance { get; set; }
        public string lieu_naissance { get; set; }
        public Nullable<System.DateTime> date_inscrip { get; set; }
        public string statut { get; set; }
        public string statut_civil { get; set; }
        public string position { get; set; }
        public Nullable<decimal> SommeDons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payement> Payement { get; set; }
    }
}
