//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payement()
        {
            this.Donation = new HashSet<Donation>();
        }
    
        public int id { get; set; }
        public int membre_id { get; set; }
        public string methode_payement { get; set; }
        public decimal somme_argent { get; set; }
        public Nullable<System.DateTime> date_payement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        public virtual Membre Membre { get; set; }
    }
}
